# Generated by Django 5.1.4 on 2024-12-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_audiobook_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('old', 'Old'), ('latest', 'Latest')], default='latest', max_length=6),
        ),
    ]
